//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace back_office.Interfaz.web.ConfiguracionPuestosPlaya {
    
    
    public partial class web_2_modificarInventario {
        
        /// <summary>
        /// mensajeDeEstado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::back_office.Interfaz.web.ConfiguracionPuestosPlaya.componentes.mensajeDeError mensajeDeEstado;
        
        /// <summary>
        /// formularioModificarInventario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::back_office.Interfaz.web.ConfiguracionPuestosPlaya.componentes.formularioModificarInventario formularioModificarInventario;
    }
}
