//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Presentacion.Vistas.Web.ConfiguracionPuestosPlaya {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosInterfaz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosInterfaz() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Presentacion.Vistas.Web.ConfiguracionPuestosPlaya.RecursosInterfaz", typeof(RecursosInterfaz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string AccionDelete {
            get {
                return ResourceManager.GetString("AccionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        internal static string AccionUpdate {
            get {
                return ResourceManager.GetString("AccionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string ComandoEliminar {
            get {
                return ResourceManager.GetString("ComandoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string ComandoModificar {
            get {
                return ResourceManager.GetString("ComandoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion actual de la Playa.
        /// </summary>
        internal static string configuracionDeLaPlaya {
            get {
                return ResourceManager.GetString("configuracionDeLaPlaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcion.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta Columna.
        /// </summary>
        internal static string ErrorColumnaNull {
            get {
                return ResourceManager.GetString("ErrorColumnaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta Fila.
        /// </summary>
        internal static string ErrorFilaNull {
            get {
                return ResourceManager.GetString("ErrorFilaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivado.
        /// </summary>
        internal static string EstadoDesactivado {
            get {
                return ResourceManager.GetString("EstadoDesactivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idcolumna.
        /// </summary>
        internal static string IdColumna {
            get {
                return ResourceManager.GetString("IdColumna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idfila.
        /// </summary>
        internal static string IdFila {
            get {
                return ResourceManager.GetString("IdFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guarda el id inventario a pasar por session.
        /// </summary>
        internal static string IdInventario {
            get {
                return ResourceManager.GetString("IdInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvTipo.
        /// </summary>
        internal static string InvTipo {
            get {
                return ResourceManager.GetString("InvTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo modificar el item del Inventario.
        /// </summary>
        internal static string mensajeDeErrorModificarInventario {
            get {
                return ResourceManager.GetString("mensajeDeErrorModificarInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se asigno exitosamente el nuevo item al Inventario.
        /// </summary>
        internal static string mensajeDeExitoAgregarInventario {
            get {
                return ResourceManager.GetString("mensajeDeExitoAgregarInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se asigno exitosamente el nuevo item a la playa.
        /// </summary>
        internal static string mensajeDeExitoAgregarPuesto {
            get {
                return ResourceManager.GetString("mensajeDeExitoAgregarPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La configuracion de la playa fue cambiada exitosamente.
        /// </summary>
        internal static string mensajeDeExitoConfigurarPlaya {
            get {
                return ResourceManager.GetString("mensajeDeExitoConfigurarPlaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico exitosamente el item del Inventario.
        /// </summary>
        internal static string mensajeDeExitoModificarInventario {
            get {
                return ResourceManager.GetString("mensajeDeExitoModificarInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se modifico exitosamente el puesto de la playa.
        /// </summary>
        internal static string mensajeDeExitoModificarPuesto {
            get {
                return ResourceManager.GetString("mensajeDeExitoModificarPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web_2_consultarInventario.aspx.
        /// </summary>
        internal static string PaginaConsultarInventario {
            get {
                return ResourceManager.GetString("PaginaConsultarInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web_2_consultarPuesto.aspx.
        /// </summary>
        internal static string PaginaConsultarPuesto {
            get {
                return ResourceManager.GetString("PaginaConsultarPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web_2_modificarInventario.aspx.
        /// </summary>
        internal static string PaginaModificarInventario {
            get {
                return ResourceManager.GetString("PaginaModificarInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web_2_modificarPuesto.aspx.
        /// </summary>
        internal static string PaginaModificarPuesto {
            get {
                return ResourceManager.GetString("PaginaModificarPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to precio.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se consiguio ningun registro.
        /// </summary>
        internal static string RegistrosVacios {
            get {
                return ResourceManager.GetString("RegistrosVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web_2_consultarPuesto.aspx.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Columnas.
        /// </summary>
        internal static string textoColumnasPor {
            get {
                return ResourceManager.GetString("textoColumnasPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Filas por .
        /// </summary>
        internal static string textoFilasPor {
            get {
                return ResourceManager.GetString("textoFilasPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textoVacio {
            get {
                return ResourceManager.GetString("textoVacio", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Puesto Eliminado con exito.
        /// </summary>
        internal static string MensajeExitoEliminarPuesto
        {
            get
            {
                return ResourceManager.GetString("MensajeExitoEliminarPuesto", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Puesto no fue eliminado.
        /// </summary>
        internal static string MensajeErrorEliminarPuesto
        {
            get
            {
                return ResourceManager.GetString("MensajeErrorEliminarPuesto", resourceCulture);
            }
        }
    }
}
