//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.FuenteDatos.Dao.Proveedores.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosDaoProveedores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosDaoProveedores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.FuenteDatos.Dao.Proveedores.Recursos.RecursosDaoProveedores", typeof(RecursosDaoProveedores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activado.
        /// </summary>
        internal static string Activado {
            get {
                return ResourceManager.GetString("Activado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        internal static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudades de Estado.
        /// </summary>
        internal static string CiudadesDeEstados {
            get {
                return ResourceManager.GetString("CiudadesDeEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string Consultar {
            get {
                return ResourceManager.GetString("Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Busqueda.
        /// </summary>
        internal static string ConsultarBusq {
            get {
                return ResourceManager.GetString("ConsultarBusq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Ciudades.
        /// </summary>
        internal static string ConsultarCiudades {
            get {
                return ResourceManager.GetString("ConsultarCiudades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Direccion.
        /// </summary>
        internal static string ConsultarDireccion {
            get {
                return ResourceManager.GetString("ConsultarDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Estados.
        /// </summary>
        internal static string ConsultarEstados {
            get {
                return ResourceManager.GetString("ConsultarEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Estados De Pais.
        /// </summary>
        internal static string ConsultarEstadosPais {
            get {
                return ResourceManager.GetString("ConsultarEstadosPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Paises.
        /// </summary>
        internal static string ConsultarPaises {
            get {
                return ResourceManager.GetString("ConsultarPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar todos los proveedores.
        /// </summary>
        internal static string ConsultarTodosProv {
            get {
                return ResourceManager.GetString("ConsultarTodosProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaoProveedor.
        /// </summary>
        internal static string DaoProv {
            get {
                return ResourceManager.GetString("DaoProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivado.
        /// </summary>
        internal static string Desactivado {
            get {
                return ResourceManager.GetString("Desactivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han podido cargar los datos debido a que hay una referencia nula.
        /// </summary>
        internal static string ex02 {
            get {
                return ResourceManager.GetString("ex02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han podido cargar los datos debido a que existe un conflicto con la conexión a la base de datos.
        /// </summary>
        internal static string ex03 {
            get {
                return ResourceManager.GetString("ex03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han podido cargar los datos debido a un error en el sistema.
        /// </summary>
        internal static string ex04 {
            get {
                return ResourceManager.GetString("ex04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items de Proveedor.
        /// </summary>
        internal static string ItemsProv {
            get {
                return ResourceManager.GetString("ItemsProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _paramBusq.
        /// </summary>
        internal static string paramBusq {
            get {
                return ResourceManager.GetString("paramBusq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _proCiudad.
        /// </summary>
        internal static string paramCiudad {
            get {
                return ResourceManager.GetString("paramCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _proCorreo.
        /// </summary>
        internal static string paramCorreo {
            get {
                return ResourceManager.GetString("paramCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _proDireccion.
        /// </summary>
        internal static string paramDireccion {
            get {
                return ResourceManager.GetString("paramDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _proFechaContrato.
        /// </summary>
        internal static string paramFechaContrato {
            get {
                return ResourceManager.GetString("paramFechaContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idDireccion.
        /// </summary>
        internal static string paramIdDireccion {
            get {
                return ResourceManager.GetString("paramIdDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _proId.
        /// </summary>
        internal static string paramProId {
            get {
                return ResourceManager.GetString("paramProId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _provId.
        /// </summary>
        internal static string paramProvId {
            get {
                return ResourceManager.GetString("paramProvId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _proRazonSocial.
        /// </summary>
        internal static string paramRazonSocial {
            get {
                return ResourceManager.GetString("paramRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _proRif.
        /// </summary>
        internal static string paramRif {
            get {
                return ResourceManager.GetString("paramRif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _proStatus.
        /// </summary>
        internal static string paramStatus {
            get {
                return ResourceManager.GetString("paramStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _proTelefono.
        /// </summary>
        internal static string paramTlf {
            get {
                return ResourceManager.GetString("paramTlf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _proPaginaWeb.
        /// </summary>
        internal static string paramWeb {
            get {
                return ResourceManager.GetString("paramWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_AlmacenarProveedor.
        /// </summary>
        internal static string PcdAlmacenarProv {
            get {
                return ResourceManager.GetString("PcdAlmacenarProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_cargarItemLT.
        /// </summary>
        internal static string PcdCargarItemLT {
            get {
                return ResourceManager.GetString("PcdCargarItemLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_consultarDireccionProveedor.
        /// </summary>
        internal static string PcdConsDireccion {
            get {
                return ResourceManager.GetString("PcdConsDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_consultarProveedorGeneral.
        /// </summary>
        internal static string PcdConsultarProv {
            get {
                return ResourceManager.GetString("PcdConsultarProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_eliminarProveedor.
        /// </summary>
        internal static string PcdEliminarProv {
            get {
                return ResourceManager.GetString("PcdEliminarProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_llenarGVProveedores.
        /// </summary>
        internal static string PcdLlenarGV {
            get {
                return ResourceManager.GetString("PcdLlenarGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_modificarProveedor.
        /// </summary>
        internal static string PcdModificarProv {
            get {
                return ResourceManager.GetString("PcdModificarProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ObtenerCiudadesEstado.
        /// </summary>
        internal static string PcdObtenerCiudadesEstado {
            get {
                return ResourceManager.GetString("PcdObtenerCiudadesEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ObtenerEstadosPais.
        /// </summary>
        internal static string PcdObtenerEstadosPais {
            get {
                return ResourceManager.GetString("PcdObtenerEstadosPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ObtenerTodosLasCiudades.
        /// </summary>
        internal static string PcdObtenerTodosCiudades {
            get {
                return ResourceManager.GetString("PcdObtenerTodosCiudades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ObtenerTodosLosEstados.
        /// </summary>
        internal static string PcdObtenerTodosEstados {
            get {
                return ResourceManager.GetString("PcdObtenerTodosEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_ObtenerTodosLosPaises.
        /// </summary>
        internal static string PcdObtenerTodosPaises {
            get {
                return ResourceManager.GetString("PcdObtenerTodosPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS_08_002.
        /// </summary>
        internal static string rs02 {
            get {
                return ResourceManager.GetString("rs02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS_08_003.
        /// </summary>
        internal static string rs03 {
            get {
                return ResourceManager.GetString("rs03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS_08_004.
        /// </summary>
        internal static string rs04 {
            get {
                return ResourceManager.GetString("rs04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Vacio {
            get {
                return ResourceManager.GetString("Vacio", resourceCulture);
            }
        }
    }
}
