//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.FuenteDatos.Dao.ConfiguracionServiciosPlaya {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosExcepcionDaoServiciosPlaya {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosExcepcionDaoServiciosPlaya() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.FuenteDatos.Dao.ConfiguracionServiciosPlaya.RecursosExcepcionDaoServic" +
                            "iosPlaya", typeof(RecursosExcepcionDaoServiciosPlaya).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DaoServiciosPlaya.
        /// </summary>
        internal static string claseDaoServiciosPlaya {
            get {
                return ResourceManager.GetString("claseDaoServiciosPlaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CSP_03_003.
        /// </summary>
        internal static string codigoErrorGeneral {
            get {
                return ResourceManager.GetString("codigoErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CSP_03_001.
        /// </summary>
        internal static string codigoErrorNullReference {
            get {
                return ResourceManager.GetString("codigoErrorNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CSP_03_002.
        /// </summary>
        internal static string codigoErrorSql {
            get {
                return ResourceManager.GetString("codigoErrorSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En estos momentos no podemos procesar su solicitud..
        /// </summary>
        internal static string mensajeGeneral {
            get {
                return ResourceManager.GetString("mensajeGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo establecer conexión con el sistema..
        /// </summary>
        internal static string mensajeNullReference {
            get {
                return ResourceManager.GetString("mensajeNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se generó un error en el proveedor de datos del sistema..
        /// </summary>
        internal static string mensajeSql {
            get {
                return ResourceManager.GetString("mensajeSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConsultarServicios.
        /// </summary>
        internal static string metodoConsultarServicios {
            get {
                return ResourceManager.GetString("metodoConsultarServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EliminarServicioPlaya.
        /// </summary>
        internal static string metodoEliminarServicioPlaya {
            get {
                return ResourceManager.GetString("metodoEliminarServicioPlaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TransformaServicio.
        /// </summary>
        internal static string metodoTransformaServicio {
            get {
                return ResourceManager.GetString("metodoTransformaServicio", resourceCulture);
            }
        }
    }
}
