//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.FuenteDatos.Dao.VentaCierreCaja.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosDaoCierreCaja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosDaoCierreCaja() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.FuenteDatos.Dao.VentaCierreCaja.Recursos.RecursosDaoCierreCaja", typeof(RecursosDaoCierreCaja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @correo.
        /// </summary>
        internal static string ParametroCorreo {
            get {
                return ResourceManager.GetString("ParametroCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_buscarCorreosClientes.
        /// </summary>
        internal static string ProcedimientoConsultarCorreosClientes {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarCorreosClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_consultarGridPorCorreo.
        /// </summary>
        internal static string ProcedimientoGridServicios {
            get {
                return ResourceManager.GetString("ProcedimientoGridServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_verificarCorreoUsuario.
        /// </summary>
        internal static string ProcedimientoVerificarCorreo {
            get {
                return ResourceManager.GetString("ProcedimientoVerificarCorreo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_consultarFaacturas.
        /// </summary>
        internal static string ProcedimientoConsultarFacturas
        {
            get
            {
                return ResourceManager.GetString("ProcedimientoConsultarFacturas", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a @_busqueda.
        /// </summary>
        internal static string ParametroBusqueda
        {
            get
            {
                return ResourceManager.GetString("ParametroBusqueda", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Busca una cadena traducida similar a @_estado.
        /// </summary>
        internal static string ParametroEstado
        {
            get
            {
                return ResourceManager.GetString("ParametroEstado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_eliminarFaactura.
        /// </summary>
        internal static string ProcedimientoEliminarFacturas
        {
            get
            {
                return ResourceManager.GetString("ProcedimientoEliminarFacturas", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a @_nroFactura.
        /// </summary>
        internal static string ParametroNroFactura
        {
            get
            {
                return ResourceManager.GetString("ParametroNroFactura", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a RetVal.
        /// </summary>
        internal static string ParametroRetorno
        {
            get
            {
                return ResourceManager.GetString("ParametroRetorno", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_datoFactura.
        /// </summary>
        internal static string ProcedimientoDatosBasicosFactura
        {
            get
            {
                return ResourceManager.GetString("ProcedimientoDatosBasicosFactura", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_datosClienteFactura.
        /// </summary>
        internal static string ProcedimientoDatosCliente
        {
            get
            {
                return ResourceManager.GetString("ProcedimientoDatosCliente", resourceCulture);
            }
        }


        /// <summary>
        ///   Busca una cadena traducida similar a Procedure_consultarLineaFactura.
        /// </summary>
        internal static string ProcedimientoLineasFacturas
        {
            get
            {
                return ResourceManager.GetString("ProcedimientoLineasFacturas", resourceCulture);
            }
        }


    }
}
