//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.LogicaNegocio.Comandos.ConfiguracionPuestosPlaya {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosComando {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosComando() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.LogicaNegocio.Comandos.ConfiguracionPuestosPlaya.RecursosComando", typeof(RecursosComando).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComandoActualizarInventarioTipo.
        /// </summary>
        internal static string ClaseComandoActualizarInventarioTipo {
            get {
                return ResourceManager.GetString("ClaseComandoActualizarInventarioTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComandoActualizarItemSeleccionado.
        /// </summary>
        internal static string ClaseComandoActualizarItemSeleccionado {
            get {
                return ResourceManager.GetString("ClaseComandoActualizarItemSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComandoConsultarEstadosInventario.
        /// </summary>
        internal static string ClaseComandoConsultarEstadosInventario {
            get {
                return ResourceManager.GetString("ClaseComandoConsultarEstadosInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComandoConsultarInventarioTipo.
        /// </summary>
        internal static string ClaseComandoConsultarInventarioTipo {
            get {
                return ResourceManager.GetString("ClaseComandoConsultarInventarioTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComandoConsultarInventarioXId.
        /// </summary>
        internal static string ClaseComandoConsultarInventarioXId {
            get {
                return ResourceManager.GetString("ClaseComandoConsultarInventarioXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComandoEliminarItemSeleccionado.
        /// </summary>
        internal static string ClaseComandoEliminarItemSeleccionado {
            get {
                return ResourceManager.GetString("ClaseComandoEliminarItemSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPP_02_001.
        /// </summary>
        internal static string CodigoErrorGeneral {
            get {
                return ResourceManager.GetString("CodigoErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En estos momentos no podemos atender su solicitud. Por favor intente mas tarde.
        /// </summary>
        internal static string MensajeErrorExcepcion {
            get {
                return ResourceManager.GetString("MensajeErrorExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar.
        /// </summary>
        internal static string MetodoEjecutar {
            get {
                return ResourceManager.GetString("MetodoEjecutar", resourceCulture);
            }
        }
    }
}
