//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.Presentacion.Vistas.Web.RolesSeguridad.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosInterfazRolesSeguridad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosInterfazRolesSeguridad()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOffice.Presentacion.Vistas.Web.RolesSeguridad.Recursos.RecursosInterfazRolesSeguridad", typeof(RecursosInterfazRolesSeguridad).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la BD.
        /// </summary>
        internal static string mensajeConexionBD
        {
            get {
                return ResourceManager.GetString("mensajeConexionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error general.
        /// </summary>
        internal static string mensajeError
        {
            get {
                return ResourceManager.GetString("mensajeError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error BD al eliminar.
        /// </summary>
        internal static string mensajeErrorEliminacion
        {
            get
            {
                return ResourceManager.GetString("mensajeErrorEliminacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error no hay item seleccionado.
        /// </summary>
        internal static string mensajeNoSeleccionado
        {
            get
            {
                return ResourceManager.GetString("mensajeNoSeleccionado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error no ha seleccionado rol.
        /// </summary>
        internal static string mensajeElemento
        {
            get
            {
                return ResourceManager.GetString("mensajeElemento", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Exito se modifico.
        /// </summary>
        internal static string mensajeModificacion
        {
            get
            {
                return ResourceManager.GetString("mensajeModificacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error rol ya existe.
        /// </summary>
        internal static string mensajeRegistrado
        {
            get
            {
                return ResourceManager.GetString("mensajeRegistrado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exito se agrego.
        /// </summary>
        internal static string mensajeAgregado
        {
            get
            {
                return ResourceManager.GetString("mensajeAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exito se agrego.
        /// </summary>
        internal static string mensajeSesion
        {
            get
            {
                return ResourceManager.GetString("mensajeSesion", resourceCulture);
            }
        }
    }
}
